"""Add toy_latitude and toy_longitude to Toy model

Revision ID: 0592e76f9323
Revises: 3bee307e0cb7
Create Date: 2023-07-26 14:53:13.698474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0592e76f9323'
down_revision = '3bee307e0cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toys', sa.Column('toy_latitude', sa.Float(), nullable=True))
    op.add_column('toys', sa.Column('toy_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('toys', 'toy_longitude')
    op.drop_column('toys', 'toy_latitude')
    # ### end Alembic commands ###
