"""Add user latitude and longitude

Revision ID: 3bee307e0cb7
Revises: 
Create Date: 2023-07-26 14:29:03.244941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3bee307e0cb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('toys', 'toy_latitude')
    op.drop_column('toys', 'toy_longitude')
    op.add_column('users', sa.Column('user_latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('user_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_longitude')
    op.drop_column('users', 'user_latitude')
    op.add_column('toys', sa.Column('toy_longitude', mysql.FLOAT(), nullable=True))
    op.add_column('toys', sa.Column('toy_latitude', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
